# docker-compose.yml
services:
  db:
    image: postgres:16-alpine
    container_name: air_quality_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: air_quality_db
      POSTGRES_USER: ab000641 # 測試後，我們會將其改回使用 .env 變數
      POSTGRES_PASSWORD: Ab781178 # 測試後，我們會將其改回使用 .env 變數
    volumes:
      - db_data:/var/lib/postgresql/data # 資料持久化
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ab000641 -d air_quality_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: air_quality_web
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql+psycopg2://ab000641:Ab781178@db:5432/air_quality_db # 測試後會改回
      EPA_AQI_API_KEY: ${EPA_AQI_API_KEY} # 從 .env 讀取
      LINE_CHANNEL_ACCESS_TOKEN: ${LINE_CHANNEL_ACCESS_TOKEN} # 從 .env 讀取
      LINE_CHANNEL_SECRET: ${LINE_CHANNEL_SECRET} # 從 .env 讀取
    depends_on:
      db:
        condition: service_healthy

# --- 請確保這個 volumes 區塊在檔案的頂層，與 services: 對齊 ---
volumes:
  db_data: # 定義一個名為 db_data 的卷軸