# docker-compose.yml
services:
  db:
    image: postgres:16-alpine
    container_name: air_quality_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    image: cokehuang/air_quality_monitor:latest
    container_name: air_quality_web
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      EPA_AQI_API_KEY: ${EPA_AQI_API_KEY}
      LINE_CHANNEL_ACCESS_TOKEN: ${LINE_CHANNEL_ACCESS_TOKEN}
      LINE_CHANNEL_SECRET: ${LINE_CHANNEL_SECRET}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
    command: gunicorn --bind 0.0.0.0:5001 app:app # 容器內部仍然監聽 5001

  nginx: # <--- 新增 Nginx 服務
    image: nginx:latest # 使用官方 Nginx 映像檔
    container_name: air_quality_nginx
    restart: unless-stopped
    ports:
      - "80:80"   # 將主機的 80 埠映射到 Nginx 容器的 80 埠
      - "443:443" # 將主機的 443 埠映射到 Nginx 容器的 443 埠
    volumes:
      # 掛載 Nginx 配置檔案 (這些檔案在專案目錄中，所以使用相對路徑)
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/air_quality_monitor.conf:/etc/nginx/conf.d/air_quality_monitor.conf:ro
      # 修改這裡：直接掛載 Certbot archive 目錄中的實際憑證檔案
      - /etc/letsencrypt/archive/ab000641.site/fullchain2.pem:/etc/nginx/ssl/live/ab000641.site/fullchain.pem:ro
      - /etc/letsencrypt/archive/ab000641.site/privkey2.pem:/etc/nginx/ssl/live/ab000641.site/privkey.pem:ro
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/nginx/ssl/options-ssl-nginx.conf:ro
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/nginx/ssl/ssl-dhparams.pem:ro
    depends_on:
      web:
        condition: service_started # 確保 web 服務啟動後 Nginx 才啟動

    command: /bin/sh -c "rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

volumes:
  db_data: