# docker-compose.yml
services:
  db:
    image: postgres:16-alpine
    container_name: air_quality_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis: # <-- 新增 Redis 服務 (RQ 佇列的後端)
    image: redis:7-alpine
    container_name: air_quality_redis
    restart: unless-stopped
    command: redis-server --appendonly yes # 啟用 AOF 持久化，以防重啟丟失數據
    volumes:
      - redis_data:/data # 持久化 Redis 數據到具名卷

  web:
    image: cokehuang/air_quality_monitor:latest
    container_name: air_quality_web
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      EPA_AQI_API_KEY: ${EPA_AQI_API_KEY}
      LINE_CHANNEL_ACCESS_TOKEN: ${LINE_CHANNEL_ACCESS_TOKEN}
      LINE_CHANNEL_SECRET: ${LINE_CHANNEL_SECRET}
      SECRET_KEY: ${SECRET_KEY}
      # 新增 Redis URL，供 Flask 應用程式連接 RQ
      REDIS_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started # 等待 Redis 服務啟動
    command: gunicorn --bind 0.0.0.0:5001 app:app # 容器內部仍然監聽 5001

  worker: # <-- 新增 RQ Worker 服務 (執行背景任務)
    image: cokehuang/air_quality_monitor:latest # 使用與 web 服務相同的映像
    container_name: air_quality_worker
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      EPA_AQI_API_KEY: ${EPA_AQI_API_KEY}
      LINE_CHANNEL_ACCESS_TOKEN: ${LINE_CHANNEL_ACCESS_TOKEN}
      LINE_CHANNEL_SECRET: ${LINE_CHANNEL_SECRET}
      SECRET_KEY: ${SECRET_KEY}
      REDIS_URL: redis://redis:6379/0 # Worker 也需要 Redis URL
    depends_on:
      db:
        condition: service_healthy # 等待 DB 服務健康
      redis:
        condition: service_started # 等待 Redis 服務啟動
    # 啟動 RQ worker，監聽 'aqi_queue' 佇列。請確保 app.py 中使用的佇列名稱與此一致。
    command: rq worker aqi_queue

  nginx: # <--- 新增 Nginx 服務
    image: nginx:latest # 使用官方 Nginx 映像檔
    container_name: air_quality_nginx
    restart: unless-stopped
    ports:
      - "80:80"   # 將主機的 80 埠映射到 Nginx 容器的 80 埠
      - "443:443" # 將主機的 443 埠映射到 Nginx 容器的 443 埠
    volumes:
      # 掛載 Nginx 配置檔案 (這些檔案在專案目錄中，所以使用相對路徑)
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/air_quality_monitor.conf:/etc/nginx/conf.d/air_quality_monitor.conf:ro
      # 修改這裡：直接掛載 Certbot archive 目錄中的實際憑證檔案
      - /etc/letsencrypt/live/ab000641.site/fullchain.pem:/etc/nginx/ssl/live/ab000641.site/fullchain.pem:ro
      - /etc/letsencrypt/live/ab000641.site/privkey.pem:/etc/nginx/ssl/live/ab000641.site/privkey.pem:ro
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/nginx/ssl/options-ssl-nginx.conf:ro
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/nginx/ssl/ssl-dhparams.pem:ro
    depends_on:
      web:
        condition: service_started # 確保 web 服務啟動後 Nginx 才啟動

    command: /bin/sh -c "rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

volumes:
  db_data:
  redis_data: # <--- 新增 Redis 的數據卷