# docker-compose.yml
services:
  db:
    image: postgres:16-alpine
    container_name: air_quality_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data # 資料持久化
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: air_quality_web
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      EPA_AQI_API_KEY: ${EPA_AQI_API_KEY} # 從 .env 讀取
      LINE_CHANNEL_ACCESS_TOKEN: ${LINE_CHANNEL_ACCESS_TOKEN} # 從 .env 讀取
      LINE_CHANNEL_SECRET: ${LINE_CHANNEL_SECRET} # 從 .env 讀取
    depends_on:
      db:
        condition: service_healthy

# --- 請確保這個 volumes 區塊在檔案的頂層，與 services: 對齊 ---
volumes:
  db_data: # 定義一個名為 db_data 的卷軸