"""Create initial tables for Line Messaging API models

Revision ID: 7458f474ec57
Revises: 
Create Date: 2025-07-15 17:58:08.012474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7458f474ec57'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_user_id', sa.String(length=50), nullable=False),
    sa.Column('is_subscribed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('default_threshold', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_user_id')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('county', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('aqi', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('pm25', sa.Integer(), nullable=True),
    sa.Column('pm10', sa.Integer(), nullable=True),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id')
    )
    op.create_table('line_user_station_preferences',
    sa.Column('line_user_id', sa.String(length=50), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('threshold_value', sa.Integer(), nullable=True),
    sa.Column('last_alert_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['line_user_id'], ['line_users.line_user_id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('line_user_id', 'station_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('line_user_station_preferences')
    op.drop_table('stations')
    op.drop_table('line_users')
    # ### end Alembic commands ###
