name: Deploy to EC2 via Docker Hub

on:
  push:
    branches:
      - main # 當程式碼推送到 main 分支時觸發此工作流程

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 在最新的 Ubuntu 虛擬機上運行此任務

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # 檢出 GitHub 儲存庫的程式碼

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: . # Dockerfile 和應用程式檔案的上下文路徑 (這裡指當前目錄)
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/air_quality_monitor:latest # 您的 Docker Hub 用戶名/映像名稱:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master # 一個常用的 SSH Action，用於在遠端執行命令
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Connecting to EC2 and deploying..."
          cd ~/air_quality_monitor # 進入 EC2 上的專案目錄

          # 登入 Docker Hub (在 EC2 上，以便拉取私有映像，如果您的映像是私有的)
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

          # 拉取最新的 Docker 映像
          docker pull ${{ secrets.DOCKER_USERNAME }}/air_quality_monitor:latest

          # 停止並移除舊的容器
          docker-compose down

          # 啟動新的容器 (它會使用 docker-compose.yml 中指定的新映像)
          docker-compose up -d

          echo "Deployment complete."